BEGIN;

CREATE TABLE "public"."LinkClick_new" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "linkId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "device" TEXT DEFAULT 'unknown',
    "userAgent" TEXT,
    "country" TEXT,
    "referrer" TEXT,
    CONSTRAINT "LinkClick_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "LinkClick_linkId_fkey" FOREIGN KEY ("linkId") REFERENCES "public"."Link"("id") ON DELETE CASCADE ON UPDATE CASCADE
) PARTITION BY RANGE ("createdAt");

CREATE INDEX "LinkClick_linkId_createdAt_idx" ON "public"."LinkClick_new"("linkId", "createdAt");
CREATE INDEX "LinkClick_device_idx" ON "public"."LinkClick_new"("device");
CREATE INDEX "LinkClick_referrer_idx" ON "public"."LinkClick_new"("referrer");

CREATE TABLE "public"."LinkClick_p_default" PARTITION OF "public"."LinkClick_new" DEFAULT;

INSERT INTO "public"."LinkClick_new" ("id", "linkId", "createdAt", "device", "userAgent", "country", "referrer")
OVERRIDING SYSTEM VALUE
SELECT "id", "linkId", "createdAt", "device", "userAgent", "country", "referrer" FROM "public"."LinkClick";

DROP TABLE "public"."LinkClick";
ALTER TABLE "public"."LinkClick_new" RENAME TO "LinkClick";

CREATE TABLE "public"."ProfileView_new" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "device" TEXT DEFAULT 'unknown',
    "userAgent" TEXT,
    "country" TEXT,
    "referrer" TEXT,
    CONSTRAINT "ProfileView_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "ProfileView_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE
) PARTITION BY RANGE ("createdAt");

CREATE INDEX "ProfileView_userId_createdAt_idx" ON "public"."ProfileView_new"("userId", "createdAt");
CREATE INDEX "ProfileView_device_idx" ON "public"."ProfileView_new"("device");
CREATE INDEX "ProfileView_referrer_idx" ON "public"."ProfileView_new"("referrer");

CREATE TABLE "public"."ProfileView_p_default" PARTITION OF "public"."ProfileView_new" DEFAULT;

INSERT INTO "public"."ProfileView_new" ("id", "userId", "createdAt", "device", "userAgent", "country", "referrer")
OVERRIDING SYSTEM VALUE
SELECT "id", "userId", "createdAt", "device", "userAgent", "country", "referrer" FROM "public"."ProfileView";

DROP TABLE "public"."ProfileView";
ALTER TABLE "public"."ProfileView_new" RENAME TO "ProfileView";

COMMIT;
